spring:
  application:
    name: travel-itinerary-planner
  
  datasource:
    url: jdbc:mysql://localhost:3306/travel_itinerary?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  security:
    user:
      name: admin
      password: admin

server:
  port: 8080
  servlet:
    context-path: /api

# JWT Configuration
jwt:
  secret: your-secret-key-here-make-it-long-and-secure-in-production
  expiration: 86400000 # 24 hours in milliseconds

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

# Logging
logging:
  level:
    com.travelitinerary.planner: DEBUG
    org.springframework.security: DEBUG 